/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Cart: typeof import('./src/components/Cart.vue')['default']
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    ClientInput: typeof import('./src/components/clientInput.vue')['default']
    ClientPopUp: typeof import('./src/components/clientPopUp.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MyToolbar: typeof import('./src/components/MyToolbar.vue')['default']
    ProductDetails: typeof import('./src/components/ProductDetails.vue')['default']
    ProductList: typeof import('./src/components/ProductList.vue')['default']
    ProdutListItem: typeof import('./src/components/ProdutListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
